name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  '0 8 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache apt packages
        uses: actions/cache@v2
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-apt-${{ hashFiles('**/apt.txt') }}
          restore-keys: |
            ${{ runner.os }}-apt-
      - name: Install gettext
        run: sudo apt-get update && sudo apt-get install -y gettext
      - name: 星城
        shell: bash
        env:
          XINGCHENG_OPENID: ${{ secrets.XINGCHENG_OPENID }}
          XINGCHENG_USERID: ${{ secrets.XINGCHENG_USERID }}
        run: envsubst < ./src/tocity/data.txt
      - name: 极米
        shell: bash
        env:
          XGIMI_OPENID: ${{ secrets.XGIMI_OPENID }}
          XGIMI_ACCESSTOKEN: ${{ secrets.XGIMI_ACCESSTOKEN }}
        run: ./src/xgimi/exec.sh
